### ISSUE TITLE
.NET Core 5, Error in InlineControl: Couldn't find translation of method websharper_proj.Client.ClientMain.

### ISSUE THREAD

**Issue by giuliohome** [dotnet-websharper/templates#34]
I'm just following the getting started on the latest .NET Core 5 and I'm getting the error
```

F:\Appl\websharper>dotnet new websharper-web --force
The template "WebSharper 4 Client-Server Application" was created successfully.

An update for template pack WebSharper.Templates::4.7.3.424 is available.
    install command: dotnet new -i WebSharper.Templates::4.7.3.424

F:\Appl\websharper>dotnet run
F:\Appl\websharper\websharper.csproj : error NU1108: Cycle detected.
F:\Appl\websharper\websharper.csproj : error NU1108:   websharper -> WebSharper (>= 4.7.3.446).

The build failed. Fix the build errors and run again.
```

**Comment by Jooseppi12** [comment]
The problem is not really related to WebSharper, this is a generic error when you have a project which references a nuget package with the same name. When you do `dotnet new websharper-web`, it will use your current folder's name as a project name, which in this scenario is clashing with the referenced WebSharper package.

You can check this issue for further information: https://github.com/NuGet/Home/issues/6754

**Comment by giuliohome** [comment]
Perfect thank you, renamed the folder, now I see

```
F:\Appl\websharper-proj>dotnet run
It was not possible to find any compatible framework version
The framework 'Microsoft.AspNetCore.App', version '3.1.0' was not found.
  - The following frameworks were found:
      3.0.1 at [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
      5.0.9 at [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.AspNetCore.App&framework_version=3.1.0&arch=x64&rid=win10-x64
```

Should I just change the target framework of the .proj to net50 ?

**Comment by giuliohome** [comment]
Ok, I've manually set `<TargetFramework>net50</TargetFramework>` in the .proj file,

then `dotnet restore `and `dotnet run`

**Comment by giuliohome** [comment]
Sorry I'm still getting a runtime error

```
F:\Appl\websharper-proj>dotnet run
info: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[63]
      User profile is available. Using 'C:\Users\EN21165\AppData\Local\ASP.NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.
Hosting environment: Production
Content root path: F:\Appl\websharper-proj
Now listening on: http://localhost:5000
Now listening on: https://localhost:5001
Application started. Press Ctrl+C to shut down.
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://localhost:5000/ - -
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HMATGANR174K", Request id "0HMATGANR174K:00000002": An unhandled exception was thrown by the application.
      System.Exception: Error in InlineControl: Couldn't find translation of method websharper_proj.Client.ClientMain. The method or type should have JavaScript attribute or a proxy, and the project file needs to include WebSharper.CSharp.targets
         at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1645.Invoke(String message)
         at WebSharper.Web.InlineControl.WebSharper.IRequiresResources.Encode(Info meta, Provider json)
         at <StartupCode$WebSharper-UI>.$Doc.Encode@142-1.GenerateNext(IEnumerable`1& next)
         at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImpl()
         at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.System-Collections-IEnumerator-MoveNext()
         at Microsoft.FSharp.Collections.SeqModule.ToList[T](IEnumerable`1 source)
         at Microsoft.FSharp.Primitives.Basics.List.collectToFreshConsTail[T,TResult](FSharpFunc`2 f, FSharpList`1 list, FSharpList`1 cons)
         at Microsoft.FSharp.Primitives.Basics.List.collect[T,TResult](FSharpFunc`2 f, FSharpList`1 list)
         at <StartupCode$WebSharper-UI>.$Doc.Encode@142-1.GenerateNext(IEnumerable`1& next)
         at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImpl()
         at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.System-Collections-IEnumerator-MoveNext()
         at Microsoft.FSharp.Collections.SeqModule.ToList[T](IEnumerable`1 source)
         at WebSharper.Sitelets.ContentModule.metaJson[T](Info m, Provider jP, IEnumerable`1 controls)
         at WebSharper.Sitelets.ContentModule.writeResources[a](Context ctx, IEnumerable`1 controls, FSharpFunc`2 tw)
         at WebSharper.Sitelets.ContentModule.renderHead@140.Invoke(HtmlTextWriter tw)
         at <StartupCode$WebSharper-Sitelets>.$Page.get_Default@43.Invoke(FSharpOption`1 doctype, FSharpOption`1 title, FSharpFunc`2 writeHead, FSharpFunc`2 writeBody, HtmlTextWriter writer)
         at WebSharper.Sitelets.ContentModule.writeBody@138.Invoke(Stream stream)
         at WebSharper.AspNetCore.Sitelets.writeResponseAsync@32-1.Invoke(MemoryStream _arg1)
         at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@522.Invoke(AsyncParams`1 args)
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 GET http://localhost:5000/ - - - 500 0 - 275.2130ms
```

**Comment by giuliohome** [comment]
Sorry I'm still getting a runtime error

F:\Appl\websharper-proj>dotnet run
info: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[63]
      User profile is available. Using .... as key repository and Windows DPAPI to encrypt keys at rest.
Hosting environment: Production
Content root path: F:\Appl\websharper-proj
Now listening on: http://localhost:5000
Now listening on: https://localhost:5001
Application started. Press Ctrl+C to shut down.
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://localhost:5000/ - -
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HMATGANR174K", Request id "0HMATGANR174K:00000002": An unhandled exception was thrown by the application.
      System.Exception: Error in InlineControl: Couldn't find translation of method websharper_proj.Client.ClientMain. The method or type should have JavaScript attribute or a proxy, and the project file needs to include WebSharper.CSharp.targets
         at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1645.Invoke(String message)
         at WebSharper.Web.InlineControl.WebSharper.IRequiresResources.Encode(Info meta, Provider json)
         at <StartupCode$WebSharper-UI>.$Doc.Encode@142-1.GenerateNext(IEnumerable`1& next)
         at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImpl()
         at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.System-Collections-IEnumerator-MoveNext()
         at Microsoft.FSharp.Collections.SeqModule.ToList[T](IEnumerable`1 source)
         at Microsoft.FSharp.Primitives.Basics.List.collectToFreshConsTail[T,TResult](FSharpFunc`2 f, FSharpList`1 list, FSharpList`1 cons)
         at Microsoft.FSharp.Primitives.Basics.List.collect[T,TResult](FSharpFunc`2 f, FSharpList`1 list)
         at <StartupCode$WebSharper-UI>.$Doc.Encode@142-1.GenerateNext(IEnumerable`1& next)
         at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImpl()
         at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.System-Collections-IEnumerator-MoveNext()
         at Microsoft.FSharp.Collections.SeqModule.ToList[T](IEnumerable`1 source)
         at WebSharper.Sitelets.ContentModule.metaJson[T](Info m, Provider jP, IEnumerable`1 controls)
         at WebSharper.Sitelets.ContentModule.writeResources[a](Context ctx, IEnumerable`1 controls, FSharpFunc`2 tw)
         at WebSharper.Sitelets.ContentModule.renderHead@140.Invoke(HtmlTextWriter tw)
         at <StartupCode$WebSharper-Sitelets>.$Page.get_Default@43.Invoke(FSharpOption`1 doctype, FSharpOption`1 title, FSharpFunc`2 writeHead, FSharpFunc`2 writeBody, HtmlTextWriter writer)
         at WebSharper.Sitelets.ContentModule.writeBody@138.Invoke(Stream stream)
         at WebSharper.AspNetCore.Sitelets.writeResponseAsync@32-1.Invoke(MemoryStream _arg1)
         at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@522.Invoke(AsyncParams`1 args)
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 GET http://localhost:5000/ - - - 500 0 - 275.2130ms

**Comment by giuliohome** [comment]
And in ase of `dotnet new websharper-web -lang F#` (and I set `<TargetFramework>net5.0</TargetFramework>` but I guess that this is not relevant) I get another error

```
F:\Appl\websharper-proj>dotnet run
C:\Program Files\dotnet\sdk\5.0.400\FSharp\Microsoft.FSharp.Targets(281,9): error MSB6006: "wsfsc.exe" exited with code -2147450730. [F:\Appl\websharper-proj\websharper-proj.fsproj]

The build failed. Fix the build errors and run again.
```

**Comment by giuliohome** [comment]
**Workaround: solved by installing dotnet core sdk 3.1, since the newer 5.0 alone was not enough!**

**Comment by granicz** [comment]
@giuliohome Try the latest 5.0 preview from the GitHub feed - https://github.com/orgs/dotnet-websharper/packages, this targets .NET5 specifically. Could you report back your experience whether 5.0 preview does in fact not need SDK 3.1 like WebSharper 4 does?

**Comment by giuliohome** [comment]
ok, so now I have to uninstall sdk 3.1 or start from a fresh new VM...
To be clean I think I'll go with a new virtual machine,  
Then I'll create the project as above, change the target to 5.0, run
`dotnet add PROJECT package WebSharper.FSharp --version 5.0.0.64-preview1`
and `dotnet restore `and `dotnet run`.
Ping me back if you deem my procedure is wrong.
I'll keep you updated with the result and I'll cose the issue if this owkrs

**Comment by giuliohome** [comment]
uninstalled sdk 3.1 (this was faster) and seen the original error again
deleted the reference to WebSharper.FSharp from proj and added the preview from command line
Now I see a **runtime** error similar to the C# case above:

```
F:\Appl\websharper-proj\fsharp>dotnet restore
  Determining projects to restore...
  All projects are up-to-date for restore.

F:\Appl\websharper-proj\fsharp>dotnet run
info: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[63]
      User profile is available. Using 'C:\Users\blabla\AppData\Local\ASP.NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.
Hosting environment: Production
Content root path: F:\Appl\websharper-proj\fsharp
Now listening on: http://localhost:5000
Now listening on: https://localhost:5001
Application started. Press Ctrl+C to shut down.
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://localhost:5000/ - -
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HMATJP9U150G", Request id "0HMATJP9U150G:00000002": An unhandled exception was thrown by the application.
      System.Exception: Error in InlineControl at F:\Appl\websharper-proj\fsharp\Site.fs: 43.30-43.43: Couldn't find translation of method fsharp.Client.Main. The method or type should have JavaScript attribute or a proxy, and the assembly needs to be compiled with WsFsc.exe
         at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1433.Invoke(String message) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\printf.fs:line 1433
         at WebSharper.Web.FSharpInlineControl.WebSharper.IRequiresResources.Requires(Info meta)
         at Microsoft.FSharp.Collections.Internal.IEnumerator.map@75.DoMoveNext(b& curr) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\seq.fs:line 81
         at Microsoft.FSharp.Collections.Internal.IEnumerator.MapEnumerator`1.System.Collections.IEnumerator.MoveNext() in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\seq.fs:line 68
         at Microsoft.FSharp.Core.CompilerServices.RuntimeHelpers.takeOuter@273[T,TResult](ConcatEnumerator`2 x, Unit unitVar0) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\seqcore.fs:line 274
         at Microsoft.FSharp.Core.CompilerServices.RuntimeHelpers.takeInner@266[T,TResult](ConcatEnumerator`2 x, Unit unitVar0) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\seqcore.fs:line 268
         at Microsoft.FSharp.Core.CompilerServices.RuntimeHelpers.takeInner@266[T,TResult](ConcatEnumerator`2 x, Unit unitVar0) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\seqcore.fs:line 268
         at Microsoft.FSharp.Collections.SetTreeModule.mkFromEnumerator[a](IComparer`1 comparer, SetTree`1 acc, IEnumerator`1 e) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\set.fs:line 499
         at Microsoft.FSharp.Collections.SetTreeModule.ofSeq[a](IComparer`1 comparer, IEnumerable`1 c) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\set.fs:line 505
         at WebSharper.Sitelets.ContentModule.writeResources[a](Context ctx, IEnumerable`1 controls, FSharpFunc`2 tw)
         at WebSharper.Sitelets.ContentModule.getResourcesAndScripts[a](Context ctx, IEnumerable`1 controls)
         at WebSharper.UI.SpecialHoleModule.RenderResources(SpecialHole holes, Context ctx, IEnumerable`1 reqs)
         at WebSharper.UI.Templating.Runtime.Server.write@808-2.Invoke(Context ctx, HtmlTextWriter w, Boolean r)
         at WebSharper.UI.Elt.Write(Context ctx, HtmlTextWriter h, Boolean res)
         at <StartupCode$WebSharper-UI>.$Doc.Server.Page@43-1.Invoke(Stream s)
         at WebSharper.AspNetCore.Sitelets.writeResponseAsync@32-1.Invoke(MemoryStream _arg1)
         at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt, TResult result1, FSharpFunc`2 part2) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 386
         at <StartupCode$FSharp-Core>.$Async.Return@1054.Invoke(AsyncActivation`1 ctxt) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 1054
         at <StartupCode$FSharp-Core>.$Async.Return@1054.Invoke(AsyncActivation`1 ctxt) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 1054
         at <StartupCode$FSharp-Core>.$Async.Return@1054.Invoke(AsyncActivation`1 ctxt) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 1054
         at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 104
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 GET http://localhost:5000/ - - - 500 0 - 302.7539ms
```

**Comment by giuliohome** [comment]
and the above is again magically solved if I install back dotnet-sdk-3.1.412-win-x64 (together with dotnet-sdk-5.0.400-win-x64 to target `<TargetFramework>net5.0</TargetFramework>`) and I restore `<PackageReference Include="WebSharper.FSharp" Version="4.7.3.446" />` in the fsharp.fsproj and I `dotnet restor`e and `dotnet run`

**Comment by giuliohome** [comment]
wait, I have to add all the W# preview packages, sorry...

**Comment by giuliohome** [comment]
> 
> 
> @giuliohome Try the latest 5.0 preview from the GitHub feed - https://github.com/orgs/dotnet-websharper/packages, this targets .NET5 specifically. Could you report back your experience whether 5.0 preview does in fact not need SDK 3.1 like WebSharper 4 does?

Yes, that works, _once one knows how to do that_ :-)
